# Generated by Django 5.0.6 on 2024-08-17 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('faixa_salarial', models.CharField(choices=[('0-1000', 'Até 1.000'), ('1000-2000', 'De 1.000 a 2.000'), ('2000-3000', 'De 2.000 a 3.000'), ('3000+', 'Acima de 3.000')], max_length=10)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Superior'), ('pos', 'Pós/MBA/Mestrado'), ('doutorado', 'Doutorado')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectativa_salarial', models.CharField(choices=[('0-1000', 'Até 1.000'), ('1000-2000', 'De 1.000 a 2.000'), ('2000-3000', 'De 2.000 a 3.000'), ('3000+', 'Acima de 3.000')], max_length=10)),
                ('experiencia_profissional', models.TextField()),
                ('ultima_escolaridade', models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Superior'), ('pos', 'Pós/MBA/Mestrado'), ('doutorado', 'Doutorado')], max_length=20)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='accounts.vaga')),
            ],
        ),
    ]
